ml_import_wizard/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from ml_import_wizard.views import *

app_name='ml_import_wizard'

urlpatterns = [
    path('', ManageImports.as_view(), name='import'),
    path('<int:import_scheme_id>/delete', DeleteImportScheme.as_view(), name='scheme_delete'),
    path('<int:import_scheme_id>', DoImportScheme.as_view(), name='scheme'),
    path('<int:import_scheme_id>/list', ListImportSchemeItems.as_view(), name='scheme_list_items'),
    
    path('<int:import_scheme_id>/preview', PreviewImportScheme.as_view(), name='scheme_preview_items'),\
    path('<int:import_scheme_id>/accept', AcceptPreviewImportScheme.as_view(), name='scheme_preview_accept'),
    path('<int:import_scheme_id>/description', DescribeImportScheme.as_view(), name='scheme_description'),
    path('<int:import_scheme_id>/<int:import_item_id>', DoImportSchemeItem.as_view(), name='scheme_item'),
    path('<int:import_scheme_id>/<str:model_name>', DoImporterModel.as_view(), name='importer_model'),
    path('<slug:importer_slug>', NewImportScheme.as_view(), name='new_scheme'),
]

ml_import_wizard/templates/ml_import_wizard/base.html
{% extends "base.html" %}
{% load static %}
{% load ml_import_wizard_tags %}

{% block header_external_content %}
    <!-- External elements -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>
{% endblock %}

{% block header_content %}
    <link rel="stylesheet" type="text/css" href="{% static 'ml_import_wizard/css/import_wizard.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.21.3/dist/bootstrap-table.min.css">
    <script src="{% static 'ml_import_wizard/js/import_wizard.js' %}"></script>
    <script src="https://unpkg.com/bootstrap-table@1.21.3/dist/bootstrap-table.min.js"></script>
{% endblock %}

ml_import_wizard/templates/ml_import_wizard/manager.html
{% extends "ml_import_wizard/base.html" %}

{% block page_content %}
So, it looks like you're wanting to import something?
<br><br>
Do you want to import something new :
<ul>
{% for importer in importers %}
<li><a href='{{ importer.importer }}''>{{ importer.name }}</a>{% if importer.description %}: {{ importer.description }}{% endif %}</li>
{% endfor %}
</ul>
{% if user_import_schemes|length %}
Or keep working with a previous import?


<div class="col-sm-12">
    <table id="example" class="table table-striped table-bordered viroverse-table-tight w-50">
        {% comment %} style="width:50%" {% endcomment %}
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Status</th>
                <th>Edit</th>
                
            </tr>
        </thead>
        <tbody>
        {% for scheme in user_import_schemes %}
            <tr>
                <td><a href='{% url 'ml_import_wizard:import' %}{{ scheme.id }}'>{{ scheme.name }}</a></td>
                <td>{{ scheme.description }}</td>
                <td><span class="status">{{ scheme.status }}</span></td>
                <td>
                    <button class="delete-scheme" data-name={{ scheme.description }} data-id="{{ scheme.id }}" data-url="{% url 'ml_import_wizard:scheme_delete' scheme.id %}">
                        <i class="fa fa-trash">  </i>
                    </button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}

<script>
    $(document).ready(function() {
        $('.delete-scheme').on('click', function() {
            var schemeId = $(this).data('id');
            var schemeName = $(this).data('name');
            var url = $(this).data('url');
            
            if (!confirm('Are you sure you want to delete:'+schemeName)) return;

            $.ajax({
                url: url,
                type: 'POST',
                headers: { 'X-CSRFToken': '{{ csrf_token }}' },
                data: ({'scheme_id': schemeId}),
                
                success: function(result) {
                    alert(result);
                    location.reload();
                },
                error: function(xhr, status, error) {
                    alert('Error deleting scheme: ' + error);
                }
            });
        });


         var schemeTable = $('#scheme').DataTable({
            
            ordering: true,
            lengthMenu: [10, 25, 50, -1]

        });


    });
</script>
{% endblock %}

ml_import_wizard/templates/ml_import_wizard/new_scheme.html
{% extends "ml_import_wizard/base.html" %}
{% load crispy_forms_tags %}

{% block page_content %}
<div class='border border-2 border-primary rounded-3 bg-light container'>
Let's get you started with a new {{ importer }} Import:<br><br>
 
{% crispy form %}
</div>
{% endblock %}

ml_import_wizard/templates/ml_import_wizard/scheme.html
{% extends "ml_import_wizard/base.html" %}

{% load crispy_forms_tags %}
{% load static %}

{% block header_content %}
<link rel="stylesheet" type="text/css" href="{% static 'ml_import_wizard/css/import_wizard.css' %}">
<script src="{% static 'ml_import_wizard/js/import_wizard.js' %}"></script>
{% endblock %}

{% block page_content %}
<div class='border border-2 border-primary rounded-3 bg-light container'>
    <fieldset class="accordion" id="import_scheme_accordion">
        <legend id='accordion_container'>{{import_scheme}}</legend>
    </fieldset>
    {% comment %} <button type="button" class="btn btn-primary mt-2 mb-2 disabled" id="preview_button">Preview Data</button> {% endcomment %}
    <a role="button" class="btn btn-primary mt-2 mb-2 disabled" id="preview_button" href="{% url 'ml_import_wizard:scheme' import_scheme_id=import_scheme.id %}\preview">Preview Data</a>
</div>

<script type="text/javascript">
    const ITEM_TEMPLATE = `{% include "ml_import_wizard/fragments/scheme_item.html" %}`;
    // const item_template='test';
    $( document ).ready(
        window.import_scheme = new ImportScheme({
            id: {{ import_scheme.id }},
            base_url: "{% url 'ml_import_wizard:scheme' import_scheme_id=import_scheme.id %}",
            accordion_container: '#import_scheme_accordion',
        })
    );
    
    // setTimeout($('.selectpicker').selectpicker(), 3000);
    
</script>
{% include "ml_import_wizard/fragments/unclosable_progress_modal.html" %}
{% endblock %}

ml_import_wizard/templates/ml_import_wizard/scheme_description.html
{% extends "ml_import_wizard/base.html" %}

{% block page_content %}
<div class="container">
    <table class="table table-striped">
        <tbody>
            <tr>
                <td>
                    Primary file: <span class="primary_file">{{ description.files.primary }}</span>
                </td>
            </tr>
            {% if description.files.secondary %}
                <tr><td>
                {% for file, link in description.files.secondary.items %}
                    Secondary file: <span class="secondary_file_{{ link.color_key }}">{{ file }}</span><br>
                    Linked on: <span class="secondary_file_{{ link.color_key }}">{{ link.secondary_field }}</span> = <span class="primary_file">{{ link.primary_field }}</span><br><br>
                {% endfor %}
                </td></tr>
            {% endif %}
            
            {% if description.items %}
                {% for model in description.models %}
                    <tr>
                        <td>
                            Model: <span class="model_name">{{ model.name }}</span>
                        </td>
                    </tr>
                    {% for item in model.items %}
                        <tr>
                            <td>
                                Field: <span class="field_name">{{ item.field }}</span>
                                Strategy: <span class="{{ item.strategy_class|default:"strategy" }}">{{ item.strategy }}</span>
                                {% if item.value %}Value: <span class="{{ item.value_class }}">{{ item.value|safe }}</span>{% endif %}
                                
                                {% for key, value in item.key_values.items %}
                                    <br>{{ key }}: <span class="{{ value.value_class }}">{{ value.value }}</span>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                {% endfor %}
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

ml_import_wizard/templates/ml_import_wizard/scheme_preview.html
{% extends "ml_import_wizard/base.html" %}

{% block page_content %}
<div class='border border-2 border-primary rounded-3 bg-light container'>
    Preview for: <b>{{import_scheme}}</b>
    <table id='datatable'></table>
    <a role="button" class="btn btn-primary mt-2 mb-2" id="approve_button" href="{% url 'ml_import_wizard:scheme_preview_accept' import_scheme_id=import_scheme.id %}">Approve Preview</a>
</div>

<script type="text/javascript">
$( document ).ready(
    $('#datatable').bootstrapTable({
      striped: true,
      pagination: true,
      showColumns: true,
      showToggle: true,
      showExport: true,
      sortable: true,
      paginationVAlign: 'both',
      pageSize: 25,
      pageList: [10, 25, 50, 100, 'ALL'],
      columns: {{ columns|safe }},
      data: {{ rows|safe }},
    })
  );
</script>
{% endblock %}